---  
- name: download tomcat
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: '{{ guacamole_temp_path }}'

- name: create work directory
  file:
   path: /work
   state: directory
   mode: 0755
   group: root
   owner: root

- name: extract tomcat packages
  unarchive:
   src: "{{ guacamole_temp_path }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
   dest: /work
   remote_src: yes

- name: Create symbolic link
  file: 
    src: /work/apache-tomcat-{{ tomcat_version }}
    dest: /work/tomcat
    state: link


- name: Create tomcat group
  group:
    name: tomcat
    state: present   

- name: Create Tomcat User
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat
      
- name: Create tomcat service
  template:
      src: tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service

- name: Reload daemon
  systemd: 
   daemon_reload: yes

- name: Enable Tomcat
  service:
    name: tomcat
    enabled: yes

